# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSbDSqNiEKcdijwInuqehMYgj2vNGJNb

IMPORT ALL LIBRARIRES
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

print("libraries import successfully!")

"""LOAD RAW CSV"""

# Raw CSV load karein
data = pd.read_csv("AAPL_stock_data.csv")

print("Dataset Shape (Rows, Columns):", data.shape)
print("\nFirst 5 Rows:")
data.head()

"""DATA CLEANING AND DATE INDEXING"""

# Unnamed: 0  rename to date
data.rename(columns={"Unnamed: 0": "Date"}, inplace=True)

# convert string date into python daytime
data["Date"] = pd.to_datetime(data["Date"])

# Primary Date sorting
data = data.sort_values("Date").reset_index(drop=True)

print("Start Date:", data["Date"].min())
print("End Date:", data["Date"].max())
print("Missing Values Check:\n", data.isnull().sum())

"""Recent Data Filtering (2015 Onwards) & Column Selection"""

# pick data from 2015 to onward
df = data[data["Date"] >= "2015-01-01"][["Date", "adjclose"]].copy()

print("2015 se lekar total records:", len(df))
print("\nFiltered Data Sample:")
df.head()

"""Train / Test Split (80% Train, 20% Test)"""

train_size = int(len(df) * 0.8)

train_df = df.iloc[:train_size]
test_df = df.iloc[train_size:]

print(f"Training Data Size: {len(train_df)} rows")
print(f"Testing Data Size: {len(test_df)} rows")

# Split boundary visualization
plt.figure(figsize=(12, 4))
plt.plot(train_df["Date"], train_df["adjclose"], label="Train Data")
plt.plot(test_df["Date"], test_df["adjclose"], label="Test Data")
plt.title("AAPL Stock Split (Train vs Test)")
plt.ylabel("Price ($)")
plt.legend()
plt.grid(True)
plt.show()

""" Normalization (MinMax Scaling)"""

scaler = MinMaxScaler(feature_range=(0, 1))

# Fit and transform ONLY on training set to prevent Data Leakage
train_scaled = scaler.fit_transform(train_df[["adjclose"]])

# Combine train tail + test for sequence generation
total_prices = pd.concat([train_df["adjclose"], test_df["adjclose"]], axis=0).values.reshape(-1, 1)
total_scaled = scaler.transform(total_prices)

print("First 5 scaled values (0 to 1 range):")
print(train_scaled[:5])

"""Create 60-Day Sliding Window Sequences"""

def create_sequences(dataset, start_idx, end_idx, time_step=60):
    X, y = [], []
    for i in range(start_idx + time_step, end_idx):
        X.append(dataset[i - time_step:i, 0])
        y.append(dataset[i, 0])
    return np.array(X), np.array(y)

time_step = 60

X_train, y_train = create_sequences(total_scaled, 0, train_size, time_step)
X_test, y_test = create_sequences(total_scaled, train_size - time_step, len(total_scaled), time_step)

# Reshape it for LSTM: (samples, time_steps, features)
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1], 1)
X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)

print("X_train shape (Samples, Timesteps, Features):", X_train.shape)
print("X_test shape:", X_test.shape)

"""LSTM Architecture Define & Compile"""

model = Sequential([
    LSTM(50, return_sequences=True, input_shape=(time_step, 1)),
    Dropout(0.2),
    LSTM(50, return_sequences=False),
    Dropout(0.2),
    Dense(1)
])

model.compile(optimizer="adam", loss="mean_squared_error")
model.summary()

"""Model Training (Fitting)"""

history = model.fit(
    X_train, y_train,
    epochs=25,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

# Loss Curves Visualize Karein
plt.figure(figsize=(10, 4))
plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")
plt.title("Model Loss Trend")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.legend()
plt.grid(True)
plt.show()

"""Metrics Check for Model Evaluation"""

# Generate Test predictions
predictions = model.predict(X_test)

# Convert Scaled output into original dollar ($) values
predictions_inv = scaler.inverse_transform(predictions)
actual_inv = scaler.inverse_transform(y_test.reshape(-1, 1))

mae = mean_absolute_error(actual_inv, predictions_inv)
rmse = np.sqrt(mean_squared_error(actual_inv, predictions_inv))

print(f"Mean Absolute Error (MAE): ${mae:.2f}")
print(f"Root Mean Squared Error (RMSE): ${rmse:.2f}")

"""CHECKING R2 SCORE"""

from sklearn.metrics import r2_score
r2 = r2_score(actual_inv, predictions_inv)
print(f"R2 Score: {r2:.4f}")

# Naive Baseline (kal ki price = aaj ki prediction)
naive_pred = test_df['adjclose'].shift(1).dropna().values
naive_actual = test_df['adjclose'].iloc[1:].values
naive_mae = mean_absolute_error(naive_actual, naive_pred)
print(f"Naive Baseline MAE: ${naive_mae:.2f}  (compare this to your model's MAE)")

"""Future 7-Day Recursive Forecasting"""

# Pick recent  60 days sequence
last_60_days = total_scaled[-time_step:].reshape(1, time_step, 1)

future_predictions = []
curr_seq = last_60_days.copy()

# Single-step prediction loop for 7 future days
for _ in range(7):
    pred = model.predict(curr_seq, verbose=0)
    future_predictions.append(pred[0, 0])

    # Sliding window shift: first day remove, new prediction add
    curr_seq = np.append(curr_seq[:, 1:, :], [[[pred[0, 0]]]], axis=1)

# Convert Scaled output into dollars
future_prices = scaler.inverse_transform(np.array(future_predictions).reshape(-1, 1))

print("--- NEXT 7 DAYS FUTURE PREDICTIONS ---")
for i, price in enumerate(future_prices, 1):
    print(f"Day {i}: ${price[0]:.2f}")

"""Final Result Graph (Actual vs Predicted vs Future Forecast)"""

# Generating dates for Next 7 business trading days
last_date = df["Date"].iloc[-1]
future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=7, freq="B")

plt.figure(figsize=(14, 6))

# Comparison on Test Data
plt.plot(test_df["Date"], actual_inv, label="Actual Price", color="blue")
plt.plot(test_df["Date"], predictions_inv, label="Test Predictions", color="orange", linestyle="--")

# Agle 7 Days Future Forecast
plt.plot(future_dates, future_prices, label="7-Day Future Forecast", color="red", marker="o", linewidth=2)

plt.title("AAPL Stock Price Prediction & 7-Day Future Forecast")
plt.xlabel("Date")
plt.ylabel("Price ($)")
plt.legend()
plt.grid(True)
plt.show()

"""SAVE MODEL TO JOBLIB"""

model.save("aapl_lstm_model.keras")
import joblib
joblib.dump(scaler, "scaler.joblib")
print("Model and scaler saved!")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# import joblib
# import tensorflow as pd_tf
# from tensorflow.keras.models import load_model
# 
# st.set_page_config(page_title="AAPL Stock Predictor", layout="wide")
# 
# st.title("🧠 AAPL Stock Price Prediction using Deep Learning")
# st.write("Is web app mein pre-trained Deep Learning (LSTM) model ke zariye 7-day future stock forecast dikhaya gaya hai.")
# 
# # 1. Data Load
# @st.cache_data
# def load_data():
#     data = pd.read_csv("AAPL_stock_data.csv")
#     data.rename(columns={"Unnamed: 0": "Date"}, inplace=True)
#     data["Date"] = pd.to_datetime(data["Date"])
#     data = data.sort_values("Date").reset_index(drop=True)
#     df = data[data["Date"] >= "2015-01-01"][["Date", "adjclose"]].copy()
#     return df
# 
# # 2. Model & Scaler Load
# @st.cache_resource
# def load_files():
#     model = load_model("aapl_lstm_model.keras")
#     scaler = joblib.load("scaler.joblib")
#     return model, scaler
# 
# try:
#     df = load_data()
#     model, scaler = load_files()
# 
#     st.subheader("📊 Recent Historical Stock Data")
#     st.dataframe(df.tail(5), use_container_width=True)
# 
#     time_step = 60
# 
#     # Preprocessing & Scaling
#     scaled_data = scaler.transform(df[["adjclose"]])
# 
#     # Test Data Predictions
#     X_test, y_test = [], []
#     for i in range(time_step, len(scaled_data)):
#         X_test.append(scaled_data[i - time_step:i, 0])
#         y_test.append(scaled_data[i, 0])
# 
#     X_test = np.array(X_test)
#     X_test = X_test.reshape(X_test.shape[0], X_test.shape[1], 1)
# 
#     predictions = model.predict(X_test)
#     predictions_inv = scaler.inverse_transform(predictions)
#     actual_inv = scaler.inverse_transform(np.array(y_test).reshape(-1, 1))
# 
#     # Future 7-Day Forecasting
#     last_60_days = scaled_data[-time_step:].reshape(1, time_step, 1)
#     future_predictions = []
#     curr_seq = last_60_days.copy()
# 
#     for _ in range(7):
#         pred = model.predict(curr_seq, verbose=0)
#         future_predictions.append(pred[0, 0])
#         curr_seq = np.append(curr_seq[:, 1:, :], [[[pred[0, 0]]]], axis=1)
# 
#     future_prices = scaler.inverse_transform(np.array(future_predictions).reshape(-1, 1))
# 
#     last_date = df["Date"].iloc[-1]
#     future_dates = pd.date_range(start=last_date + pd.Timedelta(days=1), periods=7, freq="B")
# 
#     # Visualizations
#     col1, col2 = st.columns([2, 1])
# 
#     with col1:
#         st.subheader("📈 Stock Price Forecast Graph")
#         fig, ax = plt.subplots(figsize=(10, 5))
#         test_dates = df["Date"].iloc[time_step:]
# 
#         ax.plot(test_dates, actual_inv, label="Actual Price", color="blue")
#         ax.plot(test_dates, predictions_inv, label="Model Predictions", color="orange", linestyle="--")
#         ax.plot(future_dates, future_prices, label="7-Day Future Forecast", color="red", marker="o", linewidth=2)
#         ax.set_ylabel("Price ($)")
#         ax.legend()
#         ax.grid(True)
#         st.pyplot(fig)
# 
#     with col2:
#         st.subheader("🔮 Next 7 Days Prices")
#         forecast_df = pd.DataFrame({
#             "Date": future_dates.strftime('%Y-%m-%d'),
#             "Predicted Price ($)": future_prices.flatten().round(2)
#         })
#         st.table(forecast_df)
# 
# except Exception as e:
#     st.error(f"Error loading files: {e}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# numpy
# matplotlib
# scikit-learn
# tensorflow
# joblib

